name: Ansible Install Apache2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Install apache2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key1.pem
          chmod 600 key1.pem

      - name: Run Ansible
        run: ansible-playbook -i hosts main.yml --private-key key1.pem
