name: Ansible Install Apache2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/ansible

    steps:
      - uses: actions/checkout@v4

      - name: Create SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key1.pem
          chmod 600 key1.pem

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Run Ansible
        run: ansible-playbook -i inventory.ini setup.yml --private-key key1.pem
