name: Deploy EC2 and Configure Apache

on:
  workflow_dispatch:

jobs:
  create-ec2:
    uses: ./.github/workflows/terraform-ec2.yml
    secrets: inherit

  install-apache:
    needs: create-ec2
    uses: ./.github/workflows/ansible-apache.yml
    secrets: inherit