name: Create VM and install services

on:
  # workflow_call:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Create
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
        
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"


    # Get public IPs from terraform
    - name: Get Public IPs
      id: tf_output
      run: |
        IPS=$(terraform output -json public_ips | jq -r '.[]')
        echo "IPS=$IPS" >> $GITHUB_ENV

    # Create Ansible inventory file
    - name: Create Ansible Hosts File
      run: |
        mkdir -p ../ansible

        echo "[web]" > ../ansible/hosts

        for ip in $IPS
        do
          echo "$ip ansible_user=ubuntu ansible_ssh_private_key_file=key1.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ../ansible/hosts
        done

        echo "Generated inventory:"
        cat ../ansible/hosts



    # Create SSH key
    - name: Create SSH key
      working-directory: ./ansible
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key1.pem
        chmod 600 key1.pem

    # Run Ansible
    - name: Run Ansible
      working-directory: ./ansible
      run: ansible-playbook -i hosts main.yml
      