name: Terraform AWS Destroy VM

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/destroy_vm

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Import Terraform Resources
      run: |
        terraform console <<EOF > ids.txt
        [for v in var.vm_details : v.vm_id]
        EOF

        IDS=$(grep -o 'i-[a-zA-Z0-9]*' ids.txt)

        count=0
        for id in $IDS
        do
          terraform import aws_instance.vm[$count] $id || true
          count=$((count+1))
        done


    # Then destroy
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var-file="terraform.tfvars"
